# 公共配置文件
spring:
  # 支持 swagger3
  profiles:
    active: prod
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:13306/rg_intelligent
    username: root #
    password: rrrrrrg1.#
  elasticsearch:
    uris: http://localhost:19200
    username: elastic
    password: rrrrrrg1.
  data:
    redis:
      database: 1
      host: localhost
      port: 6379
      timeout: 5000
      password: rrrrrrg1.
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
  rabbitmq:
    host: #
    port: 5672
    username: #
    password: #

server:
  address: 0.0.0.0
  port: 8101
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
        same-site: none
        secure: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）

# 对象存储
# todo 需替换配置
cos:
  client:
    accessKey: #
    secretKey: #
    region: #
    bucket: #

# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: "接口文档"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.rg.intelligent.controller
  #  production: true
minio:
  endpoint: http://127.0.0.1:9000 #Minio服务所在地址
  bucketName: image #存储桶名称
  accessKey: admin #访问的key===username
  secretKey: rrrrrrg1. #访问的秘钥===password
